### ISSUE TITLE
`std::is_pod_v` deprecated in C++20

### ISSUE THREAD

**Issue by johnstairs** [DavidAce/h5pp#15]
This looks like a very nice library! I tried compiling one of the examples with C++20 (GCC 11.2) and I get following warning:

```
'std::is_pod_v<Volcano>' is deprecated: use is_standard_layout_v && is_trivial_v instead [-Werror=deprecated-declarations]
```

**Comment by DavidAce** [comment]
Thank you for pointing this out. I think I should just use `is_standard_layout_v` then... and start testing in c++20.
