### ISSUE TITLE
Overwrite cmake flag CMAKE_CXX_STANDARD

### ISSUE THREAD

**Issue by DmitryKuznecov** [DavidAce/h5pp#16]
I started using your library in my c++20 project and found behavior that I didn't expect.

I set the c++20 standard as 
`set(CMAKE_CXX_STANDARD 20)`. 
Then, in one of the libraries, I include h5pp
`find_package(h5pp REQUIRED)`.
After that, the standard is reset to 17, which I can observe
`message("CMAKE_CXX_STANDARD ${CMAKE_CXX_STANDARD}") #print CMAKE_CXX_STANDARD 17`

It's not very critical and I can set the c++20 standard manually again

**Comment by DavidAce** [comment]
Thanks for reporting it, this is certainly not the behavior I intended. 
I think I have found the cause [here](https://github.com/DavidAce/h5pp/blob/8ef52d7f4ed1fd9656041df6d9d4dd0420f3a7a7/cmake/modules/FindFilesystem.cmake#L123). This file is installed and run as part of `find_package(h5pp)` which calls `h5ppConfig.cmake`.  I'll try to encapsulate or avoid this line if possible.
