### ISSUE TITLE
How to traverse a hdf5 file with h5pp?

### ISSUE THREAD

**Issue by Fokatu** [DavidAce/h5pp#8]
I want to read a hdf5 file and generate a tree view of the file. Is it possible to do this with h5pp? thanks!

**Comment by DavidAce** [comment]
Hi! Sorry for the delay, I should really check my notification settings...

Yes, it is possible to generate a tree-view. The following member functions

```
h5pp::File::findLinks()
h5pp::File::findDatasets()
h5pp::File::findGroups()
```
default to making a recursive search starting from `/`. They all take optional arguments `searchKey, rootGroup, maxHits, maxDepth` to configure the search.

See more in [Example 7C](https://github.com/DavidAce/h5pp/blob/6ff0933824d7cf364e7f7c471cb84cf33f2faf57/examples/example-07c-search-in-file.cpp)
