### ISSUE TITLE
Can this library be use in .net enviroment?

### ISSUE THREAD

**Issue by Fokatu** [DavidAce/h5pp#9]
i.e.  C++/CLI.
Thanks!

**Comment by DavidAce** [comment]
I have no experience with .net. After a quick googling around I'm not sure why it would or wouldn't work. I certainly haven't done anything in particular to make h5pp compatible with it. 

If you know of a simple step to achieve this I can have a look, or I can consider a pull request. If it's just a minor addition to CMake, for instance, that should be fine.

**Comment by Fokatu** [comment]
Thanks for your reply. I am afraid it is difficult to use h5pp  in .net enviroment.

Another question.
How to transverse the attributes of a group or a dataset, including its content.
![image](https://user-images.githubusercontent.com/25919117/141928914-77d24719-7356-448a-ad62-1ec90b4c43fc.png)

Thanks!

**Comment by DavidAce** [comment]
Ok! Well if you find a simple way to make it work please share. It may help other users and I could add it to the readme.

For traversing attributes, I added a fully working example just a few minutes ago under [examples/example-03b-attributes-traverse.cpp](https://github.com/DavidAce/h5pp/blob/aeec2018abae05f47db0d6a491ed441af90f542d/examples/example-03b-attributes-traverse.cpp). I hope it clarifies.
